### ISSUE TITLE
code

### ISSUE THREAD

**Issue by tianlianghuanji** [TuSimple/rl-multishot-reid#4]

**Comment by tianlianghuanji** [comment]
I have never seen such an unfriendly code. There are mistakes in some places.

**Comment by SMCamila** [comment]
I'm so sorry for the poor code style and details. And also there might be some issues because of different MXNet versions. I will rewrite this project with Gluon (or PyTorch) in a more friendly style and I hope that you can wait for the new version.
If you find any mistakes please tell me, I will be really appreciate of that. Thank you.

**Comment by winstywang** [comment]
Hi, @tianlianghuanji 
If you are going to raise an issue, please be specific on the problems, not just complain. Complaint does not solve any bugs or problems. That is the foundation of good communication and collaboration. Also if you find the bugs, your PR is definitely welcomed. I close this issue for now. If needed, please feel free to open new ones specific to the problems in the codes. Thanks for your cooperation.

**Comment by ZhangYuef** [comment]
> I'm so sorry for the poor code style and details. And also there might be some issues because of different MXNet versions. I will rewrite this project with Gluon (or PyTorch) in a more friendly style and I hope that you can wait for the new version.
> If you find any mistakes please tell me, I will be really appreciate of that. Thank you.

Do you have a Pytorch version of this project now ?
